share_point:
  user: "{email}"
  password: "{password}"
  url: "https://{domain}.sharepoint.com"
  site: "https://{domain}.sharepoint.com/sites/{Name}/"
  folder: "Shared Documents/"
  file: "{Document}"
